
spring: 
   datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
   h2:
      console:
         enabled: true
         path: /h2-console      
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            generate_statistics: true
            format_sql: true
            
logging:
   level:
      org:
         hibernate:
            stat: debug
            type: debug
      
